### PR TITLE
Fixed SERVER_ env vars

### LINKED ISSUE #5: SERVER_NAME, SERVER_PORT, and SERVER_PROTOCOL sometimes wrong
It appears that Hyper does not always set this information on the URL object it sends. So sometimes defaults are inserted when it seems like actual values should be available.

### PR DESCRIPTION
**Pull request by technosophos**
After re-reading the RFC for CGI, I fixed up the SERVER_NAME and SERVER_PORT headers, and then did another pass at normalizing host and port across env vars. At some point we will still need to figure out how to correctly do SERVER_PROTOCOL, because right now it is always `http`. However, right now WAGI doesn't do HTTPS. So this is relatively safe for now.

See #67 for HTTPS support

Closes #5

Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

### CODE REVIEW

File: src/runtime/mod.rs [hunk 1]
```diff
@@ -452,6 +440,59 @@ impl Module {
...
+            Ok(s) => Some(s.to_owned()),
+        });
+
+        let mut host = uri
+            .host()
+            .map(|h| h.to_string())
+            .unwrap_or_else(|| "localhost".to_owned());
+        let mut port = uri.port_u16().unwrap_or(80).to_string();
+
+        let mut parse_host = |hdr: String| {
```
Comment (thomastaylor312) [inline src/runtime/mod.rs:466]: Any reason not to just split this out into its own function rather than capturing and mutating `host`?

**Review by radu-matei — APPROVED** [review]

**Review by thomastaylor312 — APPROVED** [review]

File: src/runtime/mod.rs (hunk 1 above)
Comment (thomastaylor312) [reply src/runtime/mod.rs:466]: Please note, this is a minor nit, so no need to address or re-review

Comment (technosophos) [reply src/runtime/mod.rs:466]: Really, the closure was just a way to keep the mutation compartmentalized and DRY. Because we can get port from one source and host from another, it makes sense to mutate host and port. I tried a few variations, and this one seemed to be the least lines of code/allocations.
